image: maven:3.9-eclipse-temurin-17

variables:
  MAVEN_OPTS: "-Dmaven.repo.local=.m2/repository"
  MAVEN_CLI_OPTS: "--batch-mode --errors --fail-at-end --show-version"

# Cache downloaded dependencies and plugins between builds
cache:
  paths:
    - .m2/repository/

stages:
  - build
  - test
  - package
  - deploy

build:
  stage: build
  script:
    - mvn $MAVEN_CLI_OPTS compile

test:
  stage: test
  script:
    - mvn $MAVEN_CLI_OPTS test
  artifacts:
    reports:
      junit: target/surefire-reports/TEST-*.xml

package:
  stage: package
  script:
    - mvn $MAVEN_CLI_OPTS package -DskipTests
  artifacts:
    paths:
      - target/*.jar
    expire_in: 1 week

deploy-dev:
  stage: deploy
  script:
    - echo "Triển khai lên môi trường development"
    - scp target/*.jar user@dev-server:/path/to/deployment/
    - ssh user@dev-server "cd /path/to/deployment/ && java -jar taskapi-0.0.1-SNAPSHOT.jar --spring.profiles.active=dev"
  environment:
    name: development
    url: http://dev-server:8080
  only:
    - develop
  when: manual

deploy-staging:
  stage: deploy
  script:
    - echo "Triển khai lên môi trường staging"
    - scp target/*.jar user@staging-server:/path/to/deployment/
    - ssh user@staging-server "cd /path/to/deployment/ && java -jar taskapi-0.0.1-SNAPSHOT.jar --spring.profiles.active=staging"
  environment:
    name: staging
    url: http://staging-server:8080
  only:
    - main
  when: manual

deploy-prod:
  stage: deploy
  script:
    - echo "Triển khai lên môi trường production"
    - scp target/*.jar user@prod-server:/path/to/deployment/
    - ssh user@prod-server "cd /path/to/deployment/ && java -jar taskapi-0.0.1-SNAPSHOT.jar --spring.profiles.active=prod"
  environment:
    name: production
    url: http://prod-server:8080
  only:
    - tags
  when: manual
before_script:
  - 'which ssh-agent || ( apt-get update -y && apt-get install openssh-client -y )'
  - eval $(ssh-agent -s)
  - echo "$SSH_PRIVATE_KEY" | tr -d '\r' | ssh-add -
  - mkdir -p ~/.ssh
  - chmod 700 ~/.ssh
  - echo "$SSH_KNOWN_HOSTS" > ~/.ssh/known_hosts
  - chmod 644 ~/.ssh/known_hosts