# Sử dụng image Maven với Java 17
image: maven:3.8-openjdk-17

# Định nghĩa các stage
stages:
  - build
  - test
  - deploy

# Build job
build:
  stage: build
  script: 
    - echo "Building application..."
    - mvn compile

# Test job
test:
  stage: test
  script:
    - echo "Running tests..."
    - mvn test

# Deploy job
deploy_development:
  stage: deploy
  script: 
    - echo "Deploying to development environment"
  only:
    - develop